matrix:
  include:
    - language: python
      python:
        - "2.7"
        - "3.6"
    - language: node_js
      python:
        - "node"
        - "8"
        - "7"
cache: pip
install:
  - pip install cookiecutter
script:
  - cookiecutter --no-input gh:rrwen/cookiecutter-reveal
  - cd template_name
  - npm install
  - npm run html
  - npm run pdf
