dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
  - "8"
python:
  - "2.7"
  - "3.6"
cache: pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - openjdk-7-jdk
install:
  - pip install cookiecutter
script:
  - cookiecutter --no-input gh:rrwen/cookiecutter-reveal
  - cd template_name
  - npm install
  - npm run html
  - npm run pdf
