language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install cookiecutter
script:
  - cookiecutter --no-input gh:rrwen/cookiecutter-reveal
  - cd template_name
  - npm install
  - npm run make