dist: trusty
sudo: required
language: python
python:
  - "2.7"
  - "3.6"
cache: pip
before_install:
  - sudo apt-get install -y nodejs
  - sudo apt-get install -y build-essential
  - sudo apt-get install npm
install:
  - pip install cookiecutter
script:
  - cookiecutter --no-input gh:rrwen/cookiecutter-reveal
  - cd template_name
  - npm install
  - npm run html
  - npm run pdf
