language: node_js
node_js:
  - "node"
  - "8"
install:
  - npm install
script:
  - git clone {{cookiecutter.github_url}}
  - cd {{cookiecutter.template_name}}
  - npm install
  - npm run html
  - npm run pdf
